# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: The Data-Sitters Club
author: The Data-Sitters Club
logo: DSClogo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

# Information about where the book exists on the web
repository:
  url: https://github.com/datasittersclub/site  # Online location of your book
  path_to_book: site  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true
  favicon: _static/images/favicon.ico
